# Generated by Django 3.0.5 on 2020-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acomment',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, db_column='UserID', max_length=8, null=True)),
                ('chapterid', models.CharField(blank=True, db_column='ChapterID', max_length=8, null=True)),
                ('content', models.CharField(db_column='Content', max_length=100)),
            ],
            options={
                'db_table': 'acomment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admonistrators',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=20)),
                ('password', models.CharField(db_column='Password', max_length=20)),
            ],
            options={
                'db_table': 'admonistrators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, db_column='userID', max_length=8, null=True)),
                ('chapterid', models.CharField(blank=True, db_column='chapterID', max_length=8, null=True)),
                ('content', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'audio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Audiothumbsup',
            fields=[
                ('thumbsup', models.IntegerField(db_column='Thumbsup', primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, db_column='userID', max_length=8, null=True)),
                ('worksid', models.CharField(blank=True, db_column='worksID', max_length=8, null=True)),
            ],
            options={
                'db_table': 'audiothumbsup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.CharField(db_column='bookID', max_length=8, primary_key=True, serialize=False)),
                ('introduction', models.CharField(db_column='Introduction', max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('bookname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ccomment',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, db_column='userID', max_length=8, null=True)),
                ('chapterid', models.CharField(blank=True, db_column='chapterID', max_length=8, null=True)),
                ('content', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ccomment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('bookid', models.CharField(blank=True, db_column='bookID', max_length=8, null=True)),
                ('contentofchapter', models.CharField(max_length=50, unique=True)),
                ('cname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'chapter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChapterthumbsUp',
            fields=[
                ('thumbs_up', models.CharField(db_column='Thumbs_up', max_length=8, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, db_column='userID', max_length=8, null=True)),
                ('chapterid', models.CharField(blank=True, db_column='chapterID', max_length=8, null=True)),
            ],
            options={
                'db_table': 'chapterthumbs_up',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, db_column='UserID', max_length=8, null=True)),
                ('audioid', models.CharField(blank=True, db_column='AudioID', max_length=8, null=True)),
                ('content', models.CharField(db_column='Content', max_length=100)),
                ('state', models.IntegerField(db_column='State')),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('personalsignature', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
